In [8]:
import pandas as pd

In [10]:
### The working directory is C:\...\ml-classification-project-1\notebooks. So we need to add  ".." at the front, meaning one level up, as "data" file is not within "notebook" file.
df = pd.read_csv("../data/credit_card_fraud_2026.csv")

In [12]:
df.head()

,transaction_id,amount_usd,merchant_category,card_type,auth_method,channel,device_type,is_foreign_transaction,hours_since_last_txn,txn_count_last_24h,...,ip_country_mismatch,billing_shipping_mismatch,cvv_retry_count,velocity_score,time_of_day_hour,day_of_week,is_ai_generated_scam_attempt,merchant_risk_score,prior_disputes,is_fraud
0,1,42.86,Restaurants,Visa,OTP,Online,Android Phone,False,13.54,2,...,False,False,0,0.1,18,3,False,42.3,0,0
1,2,4.75,Online Retail,Mastercard,3D Secure,Online,Android Phone,False,0.71,2,...,False,False,0,25.8,12,4,False,28.3,0,0
2,3,77.18,Groceries,Mastercard,3D Secure,Online,Mac,False,0.35,5,...,False,True,0,42.3,5,0,False,24.7,1,0
3,4,1.69,Streaming,Visa,No Authentication,POS,Android Phone,False,3.42,6,...,False,False,0,28.9,22,6,False,56.2,1,0
4,5,261.68,Travel,Visa,3D Secure,In-App,iPhone,False,2.43,2,...,False,False,0,3.9,2,4,False,32.7,0,0

In [15]:
df.shape

(20000, 26)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   transaction_id                20000 non-null  int64
 1   amount_usd                    20000 non-null  float64
 2   merchant_category             20000 non-null  str
 3   card_type                     20000 non-null  str
 4   auth_method                   20000 non-null  str
 5   channel                       20000 non-null  str
 6   device_type                   20000 non-null  str
 7   is_foreign_transaction        20000 non-null  bool
 8   hours_since_last_txn          20000 non-null  float64
 9   txn_count_last_24h            20000 non-null  int64
 10  distance_from_home_km         20000 non-null  float64
 11  card_age_months               20000 non-null  int64
 12  customer_age                  20000 non-null  int64
 13  account_balance_usd           20000 non-null  float64
 14  is_new_merchant               20000 non-null  bool
 15  used_vpn                      20000 non-null  bool
 16  ip_country_mismatch           20000 non-null  bool
 17  billing_shipping_mismatch     20000 non-null  bool
 18  cvv_retry_count               20000 non-null  int64
 19  velocity_score                20000 non-null  float64
 20  time_of_day_hour              20000 non-null  int64
 21  day_of_week                   20000 non-null  int64
 22  is_ai_generated_scam_attempt  20000 non-null  bool
 23  merchant_risk_score           20000 non-null  float64
 24  prior_disputes                20000 non-null  int64
 25  is_fraud                      20000 non-null  int64
dtypes: bool(6), float64(6), int64(9), str(5)
memory usage: 3.2 MB

### Question 1: How many rows/columns does df have?

#### ANS: 20000 rows, 26 columns. (Use ".shape")

In [21]:
df["is_fraud"].value_counts(normalize=True)

is_fraud
0    0.98305
1    0.01695
Name: proportion, dtype: float64

In [22]:
df.head(n=5)

,transaction_id,amount_usd,merchant_category,card_type,auth_method,channel,device_type,is_foreign_transaction,hours_since_last_txn,txn_count_last_24h,...,ip_country_mismatch,billing_shipping_mismatch,cvv_retry_count,velocity_score,time_of_day_hour,day_of_week,is_ai_generated_scam_attempt,merchant_risk_score,prior_disputes,is_fraud
0,1,42.86,Restaurants,Visa,OTP,Online,Android Phone,False,13.54,2,...,False,False,0,0.1,18,3,False,42.3,0,0
1,2,4.75,Online Retail,Mastercard,3D Secure,Online,Android Phone,False,0.71,2,...,False,False,0,25.8,12,4,False,28.3,0,0
2,3,77.18,Groceries,Mastercard,3D Secure,Online,Mac,False,0.35,5,...,False,True,0,42.3,5,0,False,24.7,1,0
3,4,1.69,Streaming,Visa,No Authentication,POS,Android Phone,False,3.42,6,...,False,False,0,28.9,22,6,False,56.2,1,0
4,5,261.68,Travel,Visa,3D Secure,In-App,iPhone,False,2.43,2,...,False,False,0,3.9,2,4,False,32.7,0,0

In [23]:
df.isna()

,transaction_id,amount_usd,merchant_category,card_type,auth_method,channel,device_type,is_foreign_transaction,hours_since_last_txn,txn_count_last_24h,...,ip_country_mismatch,billing_shipping_mismatch,cvv_retry_count,velocity_score,time_of_day_hour,day_of_week,is_ai_generated_scam_attempt,merchant_risk_score,prior_disputes,is_fraud
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

### Observation: the target value is highly imbalanced, with fraudulent transactions representing only 1.695% of all observations. Therefore, accuracy alone would be an inappropriate metric for evaluating model performance.